### ISSUE TITLE
How to differentiate between arguments properly?

### ISSUE THREAD

**Issue by NamVr** [rgov/node-shlex#17]
> shlex.split('"test" -test "this is part of "data", -and new"')

gives
> test,-test,this is part of data, -and new

expected:
> test,-test, this is part of "data" -and new

**Comment by rgov** [comment]
It's hard to interpret what you expect, can you write it in standard JavaScript array notation? For your input command, I get 3 elements:

    ["test", "-test", "this is part of data, -and new"]

We can put your argument list into a shell to see how it gets interpreted, with one argument per output line:

    $ printf '%s\n' "test" -test "this is part of "data", -and new"
    test
    -test
    this is part of data, -and new

That looks like it agrees with the output of `shlex.split` to me.

**Comment by rgov** [comment]
I think what you are trying to do is get quotation marks around the word `"data"`? If so, you cannot nest quotes like this because an open quote gets matched with the next close quote.

    "this is part of "data", -and new"
    ^----------------^    ^----------^

The correct way to do this is to use single quotes, which allow you to include a double quote inside:

    'this is part of "data", -and new'
    ^--------------------------------^

or you can use this ugly trick of stopping your double quoted string, starting a single quoted string, using a double quote, then stopping the single quoted string, and then opening a second double quoted string.

    "this is part of "'"'"data"'"'", -and new"
    ^----------------^^-^^----^^-^^----------^

You *also* need to remember to escape any quotes in your JavaScript string, e.g.,

```js
shlex.split('"this is part of "\'"\'"data"\'"\'", -and new"')
```
